name: tests in docker
on: [push, pull_request]
jobs:
  docker-tests:
    runs-on: ubuntu-18.04
    name: slurm-docker
    steps:
      - uses: actions/checkout@v2
      - name: run-test
        run: |
          bash run-test.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml