name: tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-18.04
    name: test examples
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest
      - name: black linter
        run: |
          black subway tests setup.py --check
      - name: test scripts
        run: |
		  pytest tests -vv
